### PR TITLE
First stage of Lists

### PR DESCRIPTION
**Pull request by drsooch**
This is my first attempt at lists. It seems to work? I tried to match the book in terms of syntax, but like my email said I wasn't sure how to deal with parentheses/brackets inside of racket, it always tried to evaluate something. I assume there is some macro magic that can take care of it.

Some of the typing judgements don't seem right, but I think we can defer to the check rule since we must always give a type to `nil`, `cons` etc.? 

Also, is it possible to ignore the type in certain situations? For example in a long chain of `cons` ie. `(cons Int 1 (cons Int 2 (nil Int)))` can we drop the `Int` for both the second `cons` and `nil`? I guess that would possibly fall into type inference?

### CODE REVIEW

**Comment by stchang** [comment]
Looks great. Yes, our use of s-exprs means that sometimes we can't get the surface syntax exactly the same as the book, so don't worry about that.

> Some of the typing judgements don't seem right

They are right. This explicitly-type syntax is exactly what languages like ML or Haskell do under the hood.

> Also, is it possible to ignore the type in certain situations? ... I guess that would possibly fall into type inference?

Yes, type inference is how these languages allow programmers to not write the explicit instantiation type. One way you can start implementing this is by adding "left arrow" versions of all your rules, where an "expected type" is an additional input to the rule.

**Comment by drsooch** [comment]
```racket
(define-typerule (cons τ e1 e2) ≫
  [⊢ e1 ≫ e1- ⇐ τ]
  [⊢ e2 ≫ e2- ⇐ (List τ)]
  ----------------
  [⊢ (cons- e1- e2-) ⇒ (List τ)])
```

I was more referencing this style where we explicitly pass the Type. We can then just use the left arrow to say make sure e1- and e2- have type `tau` and `(List tau)`. 

But you are saying we can do something similar to the `lambda` typerule where we explicitly write our the check and compute?

**Comment by stchang** [comment]
That's right, the type is just another argument to the constructor. Think of it like a type parameter in Java, eg `new ArrayList<Int>()` is directly equivalent to your `(nil Int)`.

It's true that real world typed languages often try to hide this explicit syntax with type inference, to varying degrees of success, but under the hood the type parameter is always there.

**Comment by drsooch** [comment]
I was having some trouble with `isnil` to accept a check rule. Not sure how to encode `tau` for the function if we have no knowledge of what `tau` should be?

**Pull request merged**
