### PR TITLE
Fix error conclusion; fixes #76

### LINKED ISSUE #76: #:error cannot reference attributes from right-hand side of infer arrow(?)
I'm getting a strange error when I try to use attributes from the right hand-side of an infer arrow in a `#:error` message. Here is an example excerpt (full code in Cur).

```racket
(define-typed-syntax Π
  ; Predicative rule
  [(_ (x:id (~datum :) τₐ) τᵣ) ≫
   [⊢ τₐ ≫ τₐ- ⇒ (~Type j:nat)]
   [[x ≫ x- : τₐ] ⊢ τᵣ ≫ τᵣ- ⇒ (~Type i:nat)]
   #:with k (max (syntax->datum #'i) (syntax->datum #'j))
   ------------------------------
   [⊢ (Π- τₐ- (λ (x-) τᵣ-)) ⇒ (Type k)]]

  ;; Error rules
  [(_ (x:id (~datum :) τₐ) τᵣ) ≫
   [⊢ τₐ ≫ τₐ- ⇒ (~Type j:nat)]
   [[x ≫ x- : τₐ] ⊢ τᵣ ≫ τᵣ- ⇒ (~Type i:nat)]
   #:when (and (attribute i) (attribute j))
   -----------------
   [#:error (type-error #:src #'τₐ #:msg "Universe inconsistency: A function's argument and return types must exist in a consistent universe, but ~a lives in universe (Type ~a) while ~a lives in universe (Type ~a)."
                        #'τₐ
                        (attribute j)
                        #'τᵣ
                        #;(syntax-property #'τᵣ 'origin)
                        (attribute i))]])
```

I get an error that `(attribute j)` is unbound in the `type-error` call, despite `(attribute j)` definitely existing.

```
;... cur/cur-lib/cur/curnel/turnstile-impl/dep-ind-cur2.rkt:93:35: attribute: not bound as a pattern variable
;   at: j
;   in: (attribute j)
```

The blamed line is the second occurance of `(attribute j)`.

### PR DESCRIPTION
**Pull request by wilbowma**

### CODE REVIEW

**Comment by stchang** [comment]
Hmm, now I'm confused. If this was the issue, shouldnt no pattern variables have been visible?

**Comment by wilbowma** [comment]
No pattern variables from the premises were visible; only the initial pattern (`pat.pat`) were visible in `last-clause.pat`.

I think this only affected `#:error` because most conclusion rules used `last-clause.body` for their output.

**Comment by stchang** [comment]
Ok I get it now. Good catch, thanks.

Sorry for being not helpful. I was confused about how to use `attribute`, and I didnt realize that `#:error` conclusions behaved differently from the other conclusions.

I'll merge this tomorrow

**Comment by wilbowma** [comment]
I don't blame you; it's tricky code.

Thanks!

--

**Pull request merged**
