### PR TITLE
Fix some of the signatures in the docs

### PR DESCRIPTION
**Pull request by iitalics**

### CODE REVIEW

**Comment by iitalics** [comment]
I just realized `type-out` was where it is for a reason (`define-syntax-category`). I wish these forms could be better organized into more sections but I guess `define-syntax-category` forces them to all be grouped together.

**Comment by stchang** [comment]
Good improvements, thanks! Yes, many of the things grouped with `define-syntax-category` could be more discoverable somewhere else.

Maybe duplicate the entry with an additional `@margin-note` saying that the form is generated by `define-syntax-category`?

**Comment by iitalics** [comment]
I've restructured the docs into sections, [in this branch](https://github.com/iitalics/macrotypes/tree/doc-improve-resection) ([new index](https://0x0.st/7nD.txt)). Many sections contain a [@margin note](https://0x0.st/7nk.png) like you suggested, and `define-syntax-category` lists the forms it generates.

I'd like to clarify as much as I can in the documentation to make it easier to learn to use Turnstile. This could include exposing some of the hidden parts (`~Any` and `type->str`, also the reexported modules) and maybe unifying some of the paramater API. Let me know if you have any specific opinions on how you think it should be organized

**Comment by stchang** [comment]
I like the new organization. Also, fine to expose `~Any` and `type->str`. What do you mean by re-exported modules? You mean the example langs?

**Pull request closed without merging**
