### PR TITLE
cherry-pick no-unicode support

### PR DESCRIPTION
**Pull request by wilbowma**
I can't use Turnstile with any proficiency in the unicode syntax.

### CODE REVIEW

**Comment by stchang** [comment]
Merging now but FYI, this will break `cur` because it only selectively imports some things from `turnstile`

**Comment by wilbowma** [comment]
Ah. I'll update cur later today.

--

**Comment by wilbowma** [comment]
Just ran cur from `turnstile-core` and it seems to work fine. All the `dep*` tests in `turnstile-lib` were already updated, and it looks like the versions in `cur-lib` are not doing as much selective importing.

**Comment by stchang** [comment]
Are you running your repo or mine (`turnstile-core` branch)? Mine is breaking. About to push a fix. Are you synced with me?

**Comment by wilbowma** [comment]
Yours. I thought I was. Maybe I didn't pull correctly.

**Comment by wilbowma** [comment]
Oh nevermind, only some of the `dep-ind` files in `curnel` were working.

**Pull request merged**
